version: '3.7'

services:
  apilaundryapp:
    container_name: apilaundryapp
    image: api-laundry-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8082:8082'
    environment:
      - PORT=8082
