version: '3.7'

volumes:
  mongo_data:
    external: true
  media:
  redis-vol:

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    networks:
      - smart_laundry_network
  
  redis_cache:
    container_name: redis_cache
    image: redis:7.0-rc-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - redis-vol:/data
    networks:
      - smart_laundry_network
  
  apilaundryapp:
    container_name: apilaundryapp
    image: api-laundry-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8082:8082'
    volumes:
      - /Users/trihariyadi/Projects/nodejs/api-smart-laundry/public/images
      # the volume above prevents our host system's node_modules to be mounted
      - media:/app/node_modules/
    depends_on:
      - mongo
      - redis_cache
    env_file: .env
    environment:
      - NODE_ENV=$NODE_ENV
      - REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET
      - ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
      - API_KEY=$API_KEY
      - MONGODB_URI=$MONGODB_URI
      - API_BASE_URl=$API_BASE_URl
    networks:
      - smart_laundry_network

networks:
  smart_laundry_network:
    name: smart_laundry_network
